use ViewAd_BMES;
CREATE TABLE IF NOT EXISTS Transactions (
    Id VARCHAR(36),
    UserId VARCHAR(36),
    Amount INT,
    `DateTime` DATETIME,
    TokenId VARCHAR(36),
    WithdrawDateTime DATETIME,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_Transactions_Id PRIMARY KEY (Id),
    CONSTRAINT FK_Transactions_UserId FOREIGN KEY (UserId) REFERENCES Users(Id),
    CONSTRAINT FK_Transactions_TokenId FOREIGN KEY (TokenId) REFERENCES Tokens(Id)
);